### ISSUE TITLE
log_bot.py setup hint error messages

### ISSUE THREAD

**Issue by drtrigon** [AbdealiJK/file-metadata#67]
A very nice message appeared when I tried to run the bot w/o pywikibot installed, very helpful! The same when I tried w/o user-config.py, but this one has a wrong hint:

```
[...] To create the user-config.py run the command `wikibot-create-config`.
```

So I could not find `wikibot-create-config` but `file-metadata/file_metadata/wikibot/generate_user_files.py` and running it solved the issue, so I guess the message has to be corrected or the script renamed.

**Comment by AbdealiLoKo** [comment]
I believe you're running the scripts in an unusual way.

To run the log_bot.py script you simply do:

```
$ wikibot-filemeta-log
```

To run the config script to make a configuration file:

```
$ wikibot-create-config
```

The main reason for exposing these as direct executable is because users need not go into the installation folder and run things.

PS: I need to document these scripts somewhere.

**Comment by AbdealiLoKo** [comment]
Update: These have now been documented at https://commons.wikimedia.org/wiki/User:AbdealiJK/file-metadata#In_a_pywikibot_script

**Comment by drtrigon** [comment]
Where are these executables? On github? In the dockers? In pip?

**Comment by AbdealiLoKo** [comment]
The executables are created by setuptools while installing using entry points: http://stackoverflow.com/questions/774824/explain-python-entry-points

**Comment by drtrigon** [comment]
Learned something new - nice - thanks!

Found it in: https://github.com/pywikibot-catfiles/file-metadata/blob/master/setup.py#L132
