### ISSUE TITLE
Implement face detection using facial landmark

### ISSUE THREAD

**Issue by AbdealiLoKo** [AbdealiJK/file-metadata#8]

**Comment by AbdealiLoKo** [comment]
As bob is surprisingly irritating to handle (Each bob package needs another bob package installed before it is installed and pip cannot handle this...) I've decided to most probably use `dlib` which has the facial landmark features too.
it also has some other nice tools, so possible we could use that instead of sklearn also ?
For now, Im just going to use it for facial landmarks ...

**Comment by drtrigon** [comment]
bob support was highly experimental anyways - partly due to the "strange" implemention. If you just get dlib working you have about the same level of implementation achieved... ;) ...everything more is an improvement.
The same holds for sklearn - I was in the process of implementing "learning" but still far from having working results. So basically anything new there is cool!! :)
dlib actually looks very nice! Wondering why I did not come across it back then... are the python wrappers new?

Am 25. Mai 2016 05:24:09 MESZ, schrieb AbdealiJK notifications@github.com:

> As bob is surprisingly irritating to handle (Each bob package needs
> another bob package installed before it is installed and pip cannot
> handle this...) I've decided to most probably use `dlib` which has the
> facial landmark features too.
> it also has some other nice tools, so possible we could use that
> instead of sklearn also ?
> For now, Im just going to use it for facial landmarks ...
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AbdealiJK/file-metadata/issues/8#issuecomment-221463738

Dr. Trigon

**Comment by AbdealiLoKo** [comment]
Done in https://github.com/AbdealiJK/file-metadata/commit/82ab507d3dd7739c5ae00c95c48d975cecee1d84
